---
- name: remove file entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^192.168.0.20'
    state: absent
    backup: yes
- name: remove file entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^192.168.137.65
    state: absent
    backup: yes

- name: remove file entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^192.168.0.10'
    state: absent
    backup: yes

- name: remove file entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^192.168.0.23'
    state: absent
    backup: yes
- name: remove file entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^192.168.0.22'
    state: absent
    backup: yes
- name: remove file entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^192.168.0.21'
    state: absent
    backup: yes
- name: remove file entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^192.168.0.20'
    state: absent
    backup: yes

- name: remove file entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^192.168.137.65'
    state: absent
    backup: yes
- name: remove file entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^192.168.137.66'
    state: absent
    backup: yes
- name: remove file entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^192.168.137.67'
    state: absent
    backup: yes
- name: remove file entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^192.168.137.68'
    state: absent
    backup: yes


- name: host file entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "192.168.29.211       client1"
    state: present
    backup: yes
- name: host file entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "192.168.29.212       client2"
    state: present
    backup: yes
- name: host file entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "192.168.29.210       master"
    state: present
    backup: yes

- name: host file entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "192.168.29.200       server1"
    state: present
    backup: yes

