---
- name: disable swap
  shell: |
          sudo swapoff -a
          sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: stop firewalld
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: no 
